{{- if .Values.external_secrets }}
{{- range $k, $v := .Values.external_secrets }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ $k }}
spec:
  backendType: secretsManager
{{- if $v.template_type }}
  template:
    type: {{ $v.template_type }}
{{- end }}
  region: {{ $v.region }}
{{- with $v.dataFrom  }}
  dataFrom:
{{ toYaml . | indent 4 }}
{{- end }}
{{- with $v.data  }}
  data:
{{ toYaml . | indent 4 }}
{{- end }}
---
{{- end }}
{{- end }}
