// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Stock.Trading.Data;
using System;

namespace Stock.Trading.Migrations
{
    [DbContext(typeof(TradingDbContext))]
    [Migration("20180715212750_addExchangeId")]
    partial class addExchangeId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125");

            modelBuilder.Entity("Stock.Trading.Data.Entities.OrderType", b =>
                {
                    b.Property<string>("Code")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Code");

                    b.ToTable("OrderTypes");
                });

            modelBuilder.Entity("Stock.Trading.Entities.Ask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrencyPairId")
                        .IsRequired();

                    b.Property<int>("ExchangeId");

                    b.Property<decimal>("Fulfilled");

                    b.Property<DateTime>("OrderDateUtc");

                    b.Property<string>("OrderTypeCode")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<decimal>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("OrderTypeCode");

                    b.ToTable("Asks");
                });

            modelBuilder.Entity("Stock.Trading.Entities.Bid", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrencyPairId")
                        .IsRequired();

                    b.Property<int>("ExchangeId");

                    b.Property<decimal>("Fulfilled");

                    b.Property<DateTime>("OrderDateUtc");

                    b.Property<string>("OrderTypeCode")
                        .IsRequired();

                    b.Property<decimal>("Price");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.Property<decimal>("Volume");

                    b.HasKey("Id");

                    b.HasIndex("OrderTypeCode");

                    b.ToTable("Bids");
                });

            modelBuilder.Entity("Stock.Trading.Entities.Deal", b =>
                {
                    b.Property<Guid>("DealId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid>("AskId");

                    b.Property<Guid>("BidId");

                    b.Property<DateTime>("DealDateUtc");

                    b.Property<decimal>("Price");

                    b.Property<decimal>("Volume");

                    b.HasKey("DealId");

                    b.HasIndex("AskId");

                    b.HasIndex("BidId");

                    b.ToTable("Deals");
                });

            modelBuilder.Entity("Stock.Trading.Entities.Ask", b =>
                {
                    b.HasOne("Stock.Trading.Data.Entities.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stock.Trading.Entities.Bid", b =>
                {
                    b.HasOne("Stock.Trading.Data.Entities.OrderType", "OrderType")
                        .WithMany()
                        .HasForeignKey("OrderTypeCode")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Stock.Trading.Entities.Deal", b =>
                {
                    b.HasOne("Stock.Trading.Entities.Ask", "Ask")
                        .WithMany("DealList")
                        .HasForeignKey("AskId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Stock.Trading.Entities.Bid", "Bid")
                        .WithMany("DealList")
                        .HasForeignKey("BidId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
